---
title: "Tidymodels"
author: "Jared"
date: "`r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_float:
            collapsed: false
            smooth_scroll: true
        number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```

# Packages {#packages}

```{r load-packages}
library(dplyr)
library(ggplot2)
library(rsample)
library(recipes)
```

# Data {#data}

```{r load-data}
data(credit_data, package='modeldata')
credit <- as_tibble(credit_data)

credit
```

# Create Fake "New" Data {#FakeData}

```{r fake-data}
fake <- credit |> 
    slice_sample(n=10) |> 
    select(-Status)
fake
```

# Split into Train and Test {#TrainTestsplit}

`{rsample}`

```{r split-data}
set.seed(1234)
sample(10, 4)

set.seed(1234)
credit_split <- initial_split(credit, prop=0.85, strata='Status')
credit_split

train <- training(credit_split)
test <- testing(credit_split)

train
test
```

# Preprocess Data AKA Feature Engineering {#recipes}

Load `{recipes}`

```{r check-balance}
ggplot(train, aes(x=Status)) + geom_bar()
```


```{r recipe}
recipe(Status ~ ., data=train) |>
    # not necessary with xgboost
    themis::step_upsample(Status) |>
    # not necessary with xgboost
    step_impute_knn(all_numeric_predictors()) |> 
    # not necessary with xgboost
    step_factor2string(all_nominal_predictors()) |> 
    # step_mutate(Home=tidyr::replace_na(Home, 'missing')) |> 
    # step_mutate(Job=tidyr::replace_na(Job, 'missing')) |> 
    # step_mutate(Marital=tidyr::replace_na(Marital, 'missing')) |> 
    step_mutate_at(
        all_nominal_predictors(), fn = ~ coalesce(.x, "Missing")
    ) |> 
    step_string2factor(all_nominal_predictors()) |> 
    prep(strings_as_factors=FALSE) |>
    bake(new_data=NULL)
```

